# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'OSCAR Computer Algebra System'
description:      'The OSCAR project'
url:              https://oscar.github.io
baseurl:          /oscar-website

exclude:
  - _config_production.yml
  - etc
  - LICENSE.hyde.md
  - README.hyde.md
  - README.md

kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: paragraph_end
