# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]

# Setup
title:            'The OSCAR Computer Algebra System'
tagline:          ''
description:      'The homepage of the OSCAR project'
location:         ''
url:              http://sebasguts.github.io
baseurl:          /oscar-website


exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
include: [ ]
